import type { CountryMatchProfile, MatchQuestion } from '@/types/countryMatch';

export const matchQuestions: MatchQuestion[] = [
  { id: 'budget', eyebrow: 'BUDGET', title: 'What is your comfortable monthly budget?', helper: 'Include housing and everyday living costs for your household.', options: [
    { label: 'Under €1,800', value: 'budget-low', detail: 'I need a genuinely affordable base.' }, { label: '€1,800–€2,800', value: 'budget-mid', detail: 'Value matters, with some flexibility.' }, { label: '€2,800–€4,000', value: 'budget-high', detail: 'I can prioritize location and comfort.' }, { label: 'Over €4,000', value: 'budget-premium', detail: 'Budget is not my main constraint.' },
  ] },
  { id: 'climate', eyebrow: 'CLIMATE', title: 'Which weather feels most like home?', helper: 'Think about the full year, not just holiday weather.', options: [
    { label: 'Warm and sunny', value: 'warm', detail: 'Long summers and mild winters.' }, { label: 'Four distinct seasons', value: 'seasons', detail: 'I enjoy seasonal change.' }, { label: 'Cool and mild', value: 'cool', detail: 'I would rather avoid intense heat.' },
  ] },
  { id: 'city', eyebrow: 'DAILY LIFE', title: 'What size place suits you?', helper: 'Your ideal rhythm matters more than population alone.', options: [
    { label: 'Major city', value: 'major-city', detail: 'Energy, opportunity and endless choice.' }, { label: 'Mid-sized city', value: 'mid-city', detail: 'Amenities without constant intensity.' }, { label: 'Small town', value: 'small-town', detail: 'Familiar faces and more space.' },
  ] },
  { id: 'employment', eyebrow: 'WORK', title: 'What best describes your employment?', helper: 'This helps us surface relevant—not guaranteed—visa routes.', options: [
    { label: 'Locally employed', value: 'local-work', detail: 'I expect to find a job after moving.' }, { label: 'Self-employed', value: 'self-employed', detail: 'I run a business or freelance.' }, { label: 'Retired / own income', value: 'own-income', detail: 'I will not rely on local employment.' }, { label: 'Still exploring', value: 'work-flexible', detail: 'I am open to several paths.' },
  ] },
  { id: 'remote', eyebrow: 'REMOTE WORK', title: 'Will you work remotely?', helper: 'Remote work can affect immigration, payroll and tax obligations.', options: [
    { label: 'Yes, full-time', value: 'remote', detail: 'My employer or clients are elsewhere.' }, { label: 'Hybrid or occasionally', value: 'hybrid', detail: 'Reliable connectivity still matters.' }, { label: 'No', value: 'not-remote', detail: 'Local opportunities matter more.' },
  ] },
  { id: 'language', eyebrow: 'LANGUAGES', title: 'Which language environment works for you?', helper: 'We will never assume English is sufficient for official life.', options: [
    { label: 'English-first', value: 'english', detail: 'I need to function mostly in English.' }, { label: 'Romance languages', value: 'romance', detail: 'Spanish, Portuguese, Italian or French appeal.' }, { label: 'Any language', value: 'language-flexible', detail: 'Other priorities come first.' },
  ] },
  { id: 'healthcare', eyebrow: 'HEALTHCARE', title: 'How important is healthcare access?', helper: 'Eligibility and wait times still vary by status and location.', options: [
    { label: 'Essential', value: 'healthcare', detail: 'Strong, accessible care is a top priority.' }, { label: 'Important', value: 'healthcare-balanced', detail: 'I want dependable public and private options.' }, { label: 'Flexible', value: 'healthcare-flexible', detail: 'I can arrange private coverage.' },
  ] },
  { id: 'family', eyebrow: 'FAMILY', title: 'Who are you planning around?', helper: 'Household needs can change the best city and pathway.', options: [
    { label: 'Children', value: 'family', detail: 'Schools, childcare and space matter.' }, { label: 'Partner or relatives', value: 'partner', detail: 'Family pathways are important.' }, { label: 'Just me', value: 'solo', detail: 'I can optimize for one person.' },
  ] },
  { id: 'transport', eyebrow: 'GETTING AROUND', title: 'How do you want to travel day to day?', helper: 'Country-wide transport and city transport can be very different.', options: [
    { label: 'Walk and transit', value: 'car-free', detail: 'I do not want to depend on a car.' }, { label: 'A mix', value: 'mixed-transport', detail: 'Transit plus occasional driving works.' }, { label: 'Happy to drive', value: 'car', detail: 'Road access and parking are fine.' },
  ] },
  { id: 'nature', eyebrow: 'OUTDOORS', title: 'How close should nature be?', helper: 'Choose what you want access to on an ordinary weekend.', options: [
    { label: 'Coast', value: 'coast', detail: 'Beaches and ocean air.' }, { label: 'Mountains and trails', value: 'mountains', detail: 'Hiking and dramatic landscapes.' }, { label: 'Urban parks are enough', value: 'urban-nature', detail: 'Green space without leaving the city.' },
  ] },
  { id: 'nightlife', eyebrow: 'AFTER DARK', title: 'What role should nightlife play?', helper: 'This helps distinguish lively hubs from quieter bases.', options: [
    { label: 'A lot', value: 'nightlife', detail: 'Late nights and a broad cultural scene.' }, { label: 'Sometimes', value: 'nightlife-balanced', detail: 'Good options without constant noise.' }, { label: 'Very little', value: 'quiet', detail: 'Calm evenings matter most.' },
  ] },
  { id: 'safety', eyebrow: 'SAFETY', title: 'How heavily should safety influence the match?', helper: 'No destination is risk-free; local conditions always matter.', options: [
    { label: 'Top priority', value: 'safety', detail: 'I want it weighted very heavily.' }, { label: 'Important', value: 'safety-balanced', detail: 'Balance it with lifestyle and cost.' }, { label: 'Standard precautions', value: 'safety-flexible', detail: 'I am comfortable researching neighborhoods.' },
  ] },
  { id: 'tax', eyebrow: 'TAX', title: 'How sensitive are you to taxes?', helper: 'This is a lifestyle signal, not personal tax advice.', options: [
    { label: 'Very sensitive', value: 'tax-sensitive', detail: 'Tax burden may change my decision.' }, { label: 'Somewhat', value: 'tax-balanced', detail: 'I will balance tax against services.' }, { label: 'Not a deciding factor', value: 'tax-flexible', detail: 'Lifestyle comes first.' },
  ] },
  { id: 'distance', eyebrow: 'DISTANCE', title: 'How close should home remain?', helper: 'Think about flight time, time zones and family visits.', options: [
    { label: 'A short trip away', value: 'europe-connected', detail: 'Easy regional connections matter.' }, { label: 'A medium journey', value: 'connected', detail: 'One longer flight is manageable.' }, { label: 'Anywhere', value: 'distance-flexible', detail: 'I am open to a major move.' },
  ] },
  { id: 'pace', eyebrow: 'PACE', title: 'What pace of life are you seeking?', helper: 'Imagine a typical Tuesday, not a vacation day.', options: [
    { label: 'Slow and relaxed', value: 'slow', detail: 'Time and space over urgency.' }, { label: 'Balanced', value: 'balanced', detail: 'Calm living with active options.' }, { label: 'Fast and ambitious', value: 'fast', detail: 'Career energy and momentum.' },
  ] },
  { id: 'learn', eyebrow: 'LEARNING', title: 'Would you learn another language?', helper: 'Local language skills reshape work, healthcare and community life.', options: [
    { label: 'Absolutely', value: 'learn-language', detail: 'I am ready to study seriously.' }, { label: 'Some basics', value: 'basic-language', detail: 'I will learn what daily life requires.' }, { label: 'Prefer not to', value: 'english', detail: 'I need an English-friendly base.' },
  ] },
  { id: 'international', eyebrow: 'COMMUNITY', title: 'How important is an international community?', helper: 'Consider both settling in quickly and building local ties.', options: [
    { label: 'Very important', value: 'international', detail: 'I want an established newcomer network.' }, { label: 'Nice to have', value: 'international-balanced', detail: 'A mix of local and international life.' }, { label: 'Not important', value: 'local-community', detail: 'Local immersion is the priority.' },
  ] },
];

export const countryMatchProfiles: CountryMatchProfile[] = [
  { id: 'portugal', country: 'Portugal', flag: '🇵🇹', monthlyBudget: 2780, budgetLabel: '€2,400–€3,300 / month', tags: ['warm','mid-city','remote','self-employed','romance','healthcare-balanced','partner','car-free','coast','nightlife-balanced','safety','tax-balanced','europe-connected','slow','learn-language','international'], strengths: ['Mild Atlantic climate and exceptional coastal access', 'Walkable city life in Lisbon and Porto', 'Established remote-worker and international communities'], compromises: ['Central Lisbon rent can exceed a mid-range budget', 'Portuguese is important for public services and deeper local life', 'Tax and remote-work rules need individual advice'], visaPathways: ['D8 remote-work residence or temporary stay', 'D7 own-income residence', 'D2 entrepreneur route'], cities: ['Porto', 'Braga', 'Lisbon'], unavailable: ['Your nationality and passport rights', 'Live rental availability in your chosen neighborhood'] },
  { id: 'spain', country: 'Spain', flag: '🇪🇸', monthlyBudget: 2550, budgetLabel: '€2,200–€3,200 / month', tags: ['warm','major-city','mid-city','remote','local-work','romance','healthcare','family','car-free','coast','nightlife','safety-balanced','tax-balanced','europe-connected','balanced','learn-language','international'], strengths: ['Strong public transport and healthcare framework', 'Wide choice of coastal cities and climates', 'Social, outdoor lifestyle with major international hubs'], compromises: ['Madrid and Barcelona housing can be costly', 'Spanish is important for work and administration', 'Regional tax and language differences add complexity'], visaPathways: ['International telework visa', 'Non-lucrative residence', 'Local employment permit'], cities: ['Valencia', 'Málaga', 'Madrid'], unavailable: ['Eligibility for regional healthcare on arrival', 'Employer approval for cross-border remote work'] },
  { id: 'italy', country: 'Italy', flag: '🇮🇹', monthlyBudget: 2600, budgetLabel: '€2,200–€3,300 / month', tags: ['warm','seasons','mid-city','local-work','self-employed','romance','healthcare','family','mixed-transport','coast','mountains','nightlife-balanced','safety-balanced','tax-balanced','europe-connected','slow','learn-language','local-community'], strengths: ['Unmatched variety of mid-sized cities, coast and mountains', 'Strong public healthcare framework for eligible residents', 'Rich local culture and slower everyday rhythm'], compromises: ['Administration can be slow and document-heavy', 'Italian is necessary for most local work and bureaucracy', 'Car-free living depends heavily on the city'], visaPathways: ['Digital nomad / remote worker visa', 'Elective residence visa', 'Self-employment or local work visa'], cities: ['Bologna', 'Turin', 'Trieste'], unavailable: ['Consular appointment availability', 'Exact recognition of professional qualifications'] },
  { id: 'netherlands', country: 'Netherlands', flag: '🇳🇱', monthlyBudget: 3900, budgetLabel: '€3,500–€4,800 / month', tags: ['cool','major-city','mid-city','local-work','remote','english','healthcare','partner','car-free','urban-nature','nightlife','safety','tax-flexible','europe-connected','fast','international'], strengths: ['Outstanding cycling and public-transport culture', 'English-friendly international workplaces', 'Strong services and access to connected European cities'], compromises: ['Housing is expensive and exceptionally competitive', 'Mandatory insurance and taxes raise monthly costs', 'Grey, wet winters will not suit sun seekers'], visaPathways: ['Highly skilled migrant permit', 'EU Blue Card', 'DAFT for qualifying US entrepreneurs'], cities: ['Rotterdam', 'Utrecht', 'Eindhoven'], unavailable: ['Whether an employer can sponsor you', 'A realistic housing offer at your move date'] },
  { id: 'greece', country: 'Greece', flag: '🇬🇷', monthlyBudget: 2100, budgetLabel: '€1,800–€2,700 / month', tags: ['warm','mid-city','small-town','remote','own-income','romance','healthcare-flexible','partner','car','coast','mountains','quiet','safety-balanced','tax-sensitive','connected','slow','learn-language','international-balanced'], strengths: ['Warm climate, islands and easy access to nature', 'Lower estimated costs outside the most pressured destinations', 'Relaxed pace with growing remote-work communities'], compromises: ['A car is useful outside central Athens and Thessaloniki', 'Public services and healthcare access vary by location', 'Greek is important for administration and local integration'], visaPathways: ['Digital nomad visa or residence permit', 'Financially independent person route', 'Local employment permit'], cities: ['Thessaloniki', 'Kalamata', 'Chania'], unavailable: ['Island-specific year-round healthcare capacity', 'Current tax incentive eligibility'] },
];