import type { IconName } from '@/types/travel';

export type GuideSection = {
  title: string;
  icon: IconName;
  summary: string;
  details: string[];
};

export type OfficialSource = { label: string; organization: string; url: string; checked: string };

export const italyGuide = {
  country: 'Italy',
  flag: '🇮🇹',
  title: 'Living in Italy',
  subtitle: 'A practical guide to building a life, not just planning a visit.',
  lastReviewed: '3 August 2026',
  timeSensitiveNote: 'Costs, tax, healthcare access, employment and service information were checked on 3 August 2026. Rules and prices vary by region and personal circumstances; confirm them with the linked authorities before acting.',
  quickFacts: [
    { label: 'Capital', value: 'Rome' },
    { label: 'Language', value: 'Italian' },
    { label: 'Currency', value: 'Euro (€)' },
    { label: 'Time', value: 'CET · CEST' },
  ],
  cities: [
    { name: 'Rome', note: 'Government, culture and a large, varied job market' },
    { name: 'Milan', note: 'Finance, fashion, technology and Italy’s highest housing costs' },
    { name: 'Turin', note: 'Industry, engineering and strong access to the Alps' },
    { name: 'Bologna', note: 'University life, rail connections and a walkable centre' },
    { name: 'Florence', note: 'Arts, education and tourism, with a pressured rental market' },
    { name: 'Naples', note: 'Dense urban life, lower costs and access to southern Italy' },
  ],
  sections: [
    { title: 'Languages', icon: 'globe', summary: 'Italian is the national language, alongside protected regional and minority languages.', details: ['Italian is the language of government, schooling and most workplaces. Dialects and regional languages remain part of everyday identity.', 'German is widely used in South Tyrol, French has official status in Aosta Valley, and Slovene is protected in parts of Friuli-Venezia Giulia. Other historic linguistic minorities also have legal protection.', 'Public services in multilingual regions may be available in the locally recognized language; elsewhere, expect administration to be Italian-first.'] },
    { title: 'Climate & seasons', icon: 'sun', summary: 'Alpine winters, Mediterranean summers and large regional differences.', details: ['Northern plains have cold, damp winters and hot, humid summers; snow is common in the Alps and Apennines.', 'Central regions are generally milder. The south and islands have hot, dry summers and mild, wetter winters.', 'Heatwaves, drought, flooding and wildfire risk increasingly affect daily life. Check municipal and Civil Protection alerts.'] },
    { title: 'Cost of living', icon: 'wallet', summary: 'Housing drives the budget; Milan and central Rome cost far more than smaller cities.', details: ['A realistic budget depends heavily on rent, household size and region. Groceries and local produce can be reasonable; electricity, fuel and imported goods can feel expensive.', 'Expect deposits, agency fees and setup costs when renting. Tourist centres and northern business hubs command a premium.', 'Use official ISTAT consumer-price data and live local listings rather than a single national monthly estimate. Checked 3 August 2026.'] },
    { title: 'Healthcare', icon: 'heart', summary: 'A tax-funded national service, administered regionally.', details: ['The Servizio Sanitario Nazionale (SSN) provides broad coverage through regional systems. Eligibility and registration depend on residence and status.', 'Residents normally choose a family doctor after registering with the local health authority (ASL). Co-payments can apply for tests and specialist care.', 'Quality and waiting times vary by region. Many residents use private specialists for speed; carry the European Health Insurance Card when eligible.'] },
    { title: 'Public transportation', icon: 'plane', summary: 'Excellent intercity rail; local reliability varies sharply.', details: ['High-speed and regional trains make living without a car practical in many major cities and connected towns.', 'Urban metro, tram and bus networks are strongest in Milan, Rome, Turin, Naples and other large cities, though strikes and delays occur.', 'A car is often useful in rural areas, islands and smaller southern towns. Historic centres commonly have restricted-traffic ZTL zones.'] },
    { title: 'Housing market', icon: 'home', summary: 'Competitive rentals, older buildings and paperwork-heavy contracts.', details: ['Long-term leases usually require proof of income, identity and a tax code. Registered contracts matter for residency and legal protection.', 'Older homes may have weak insulation, no lift or no air-conditioning. Ask for the energy certificate, condominium fees and heating arrangement.', 'Never transfer money before verifying the property, owner or agent and contract. Demand is especially intense in Milan, Rome, Florence and Bologna.'] },
    { title: 'Employment market', icon: 'briefcase', summary: 'Strong regional differences; Italian unlocks far more opportunities.', details: ['Manufacturing, engineering, design, tourism, food, healthcare and professional services are important sectors. Milan has the broadest international corporate market.', 'Salaries can be lower than in parts of northern Europe while payroll costs are significant. Youth unemployment and temporary contracts remain concerns.', 'EU/EEA citizens have broad work rights; others need the correct authorization. Check official visa and labour portals for current requirements. Checked 3 August 2026.'] },
    { title: 'Education & childcare', icon: 'document', summary: 'Public education is widely available; childcare supply varies locally.', details: ['State schooling is primarily in Italian. International and bilingual schools cluster around major cities and usually charge tuition.', 'Municipal nursery places can be limited and are often allocated using residence, income and family criteria. Apply early.', 'Universities include many historic public institutions, with some English-taught programs. Fees and admissions differ by institution and household circumstances.'] },
    { title: 'Banking & payments', icon: 'credit-card', summary: 'Cards are common, but cash and Italian bank details remain useful.', details: ['Merchants are generally required to accept electronic payments, yet small cash purchases remain common.', 'Opening an account typically requires identification, proof of address or status, and a codice fiscale. Fees differ, so compare account schedules.', 'An Italian IBAN can simplify rent, utilities and public administration. Keep a backup payment method for small businesses and outages.'] },
    { title: 'Internet & mobile', icon: 'globe', summary: 'Affordable mobile plans; fixed-line quality is address-specific.', details: ['4G is widespread and 5G coverage continues to expand. Prepaid SIMs are common and normally require identification.', 'Fibre availability varies building by building, even within a city. Verify the exact address before signing a lease or relying on remote work.', 'Activation can take time and customer support may be Italian-first; a temporary hotspot is useful when moving in. Checked 3 August 2026.'] },
    { title: 'Tax overview', icon: 'document', summary: 'Residence, worldwide income and regional taxes make advice worthwhile.', details: ['Tax residence can arise based on Italian statutory tests and treaty rules; residents are generally taxed on worldwide income.', 'Personal income tax is progressive, with additional regional and municipal charges. Social contributions and reporting of foreign assets may apply.', 'Special regimes exist for some inbound workers and retirees but change frequently. Get qualified cross-border advice before moving or working remotely. Checked 3 August 2026.'] },
    { title: 'Safety', icon: 'check', summary: 'Generally safe, with petty theft and environmental risks to plan for.', details: ['Pickpocketing and bag theft are the most common visitor-facing concerns, particularly on crowded transport and in tourist districts.', 'Learn local earthquake, flood, heat and wildfire procedures. Civil Protection and municipal alerts are more useful than general country rankings.', 'Emergency number 112 is available. Road safety and scooter traffic require extra attention from pedestrians and cyclists.'] },
    { title: 'Culture & etiquette', icon: 'sparkle', summary: 'Relationships, greetings and local rhythms matter.', details: ['Greet people when entering small shops, dress with context in mind and avoid treating regional identities as interchangeable.', 'Meals are social and often later than in northern Europe. Coffee and food customs are flexible, but curiosity goes over better than declaring the “right” way.', 'Administration often rewards patience, polite persistence, appointments and paper copies of every important document.'] },
    { title: 'Work-life balance', icon: 'clock', summary: 'Generous leave norms meet long commutes and uneven workplace cultures.', details: ['Collective agreements shape many working conditions, including leave and working hours. Actual flexibility varies by sector and employer.', 'Family meals, evening social life and August holidays remain important, while client-facing businesses may work split or weekend schedules.', 'Clarify remote-work terms, overtime, lunch breaks and after-hours expectations before accepting a role.'] },
    { title: 'English usage', icon: 'globe', summary: 'Useful in tourism and international workplaces, insufficient for full independence.', details: ['English is more common among younger residents, in universities, tourism and multinational companies.', 'Landlords, tradespeople, healthcare staff and public offices may operate only in Italian, especially outside large cities.', 'Basic Italian dramatically improves housing access, friendships and confidence with bureaucracy.'] },
    { title: 'Accessibility', icon: 'walk', summary: 'Legal protections exist, but historic streets and buildings create barriers.', details: ['Cobbles, steep lanes, narrow pavements, older stations and buildings without lifts can make independent movement difficult.', 'Accessible transport and services vary by operator and municipality; confirm step-free routes directly before travel or signing a lease.', 'Newer neighbourhoods are often easier to navigate. Ask for doorway, lift and bathroom measurements rather than relying on “accessible” labels.'] },
    { title: 'LGBTQ+ life', icon: 'heart', summary: 'Visible communities in major cities, with protections and social attitudes still uneven.', details: ['Same-sex civil unions are recognized, but they are not identical to marriage and family-recognition questions can be complex.', 'Milan, Rome, Bologna and Turin have established communities and events. Smaller or conservative areas may offer less visibility and support.', 'Review current rights with official and specialist organizations, particularly for partners, children and identity documents. Checked 3 August 2026.'] },
    { title: 'Pets', icon: 'heart', summary: 'Pet-friendly daily life, with formal entry and registration rules.', details: ['EU movement generally requires identification, a valid rabies vaccination and a pet passport; rules from non-EU countries vary.', 'Dogs should be registered as required locally. Landlords may set practical conditions, and condominium or municipal rules can affect shared spaces.', 'Many cafés and public spaces welcome dogs, but confirm carrier, muzzle and leash requirements for transport. Checked 3 August 2026.'] },
  ] satisfies GuideSection[],
  suitability: [
    { label: 'Remote workers', fit: 'Good fit', note: 'Strong city choice and connectivity; confirm tax and work authorization first.' },
    { label: 'Families', fit: 'Good fit', note: 'Community life and public services appeal, but childcare and housing vary locally.' },
    { label: 'Students', fit: 'Great fit', note: 'Historic universities, lively student cities and expanding English programs.' },
    { label: 'Retirees', fit: 'Good fit', note: 'Lifestyle and healthcare appeal; tax, language and car needs require planning.' },
    { label: 'Entrepreneurs', fit: 'Mixed fit', note: 'Large market and strong clusters, balanced against administration and tax complexity.' },
    { label: 'Outdoor enthusiasts', fit: 'Great fit', note: 'Alps, lakes, coasts, islands and extensive regional variety.' },
    { label: 'Car-free living', fit: 'City dependent', note: 'Excellent in rail-connected centres; difficult in many rural areas.' },
    { label: 'Lower-cost living', fit: 'City dependent', note: 'Possible away from major hubs, but local salaries and services also differ.' },
  ],
  advantages: ['Exceptional regional variety in food, landscape and city life', 'Strong intercity rail and walkable historic centres', 'Universal public healthcare framework', 'Deep community, cultural and outdoor life'],
  disadvantages: ['Slow, document-heavy administration', 'High rents in the strongest job markets', 'Lower salaries than some northern European markets', 'Large regional gaps in services and transport'],
  newcomerDifficulties: ['Securing a registered lease without local income history', 'Coordinating the tax code, residency, healthcare and bank setup', 'Navigating appointments and Italian-only paperwork', 'Understanding which rules are national, regional or municipal'],
  wishIKnew: ['Choose the neighbourhood, not just the famous city: noise, heat, transit and services change block by block.', 'Keep originals, scans and paper copies. The same document may be requested more than once.', 'Test the exact home internet address and heating costs before committing.', 'Learn Italian early; it changes daily life more than any relocation service can.'],
  sources: [
    { label: 'Living and working conditions', organization: 'European Commission · EURES', url: 'https://eures.europa.eu/living-and-working/living-and-working-conditions/living-and-working-conditions-italy_en', checked: '3 Aug 2026' },
    { label: 'Visas for Italy', organization: 'Italian Ministry of Foreign Affairs', url: 'https://vistoperitalia.esteri.it/home/en', checked: '3 Aug 2026' },
    { label: 'National Health Service', organization: 'Italian Ministry of Health', url: 'https://www.salute.gov.it/', checked: '3 Aug 2026' },
    { label: 'Taxes and taxpayer services', organization: 'Agenzia delle Entrate', url: 'https://www.agenziaentrate.gov.it/portale/web/english', checked: '3 Aug 2026' },
    { label: 'Official statistics', organization: 'ISTAT', url: 'https://www.istat.it/en/', checked: '3 Aug 2026' },
    { label: 'Civil protection alerts', organization: 'Dipartimento della Protezione Civile', url: 'https://www.protezionecivile.gov.it/en/', checked: '3 Aug 2026' },
    { label: 'Bringing pets into the EU', organization: 'European Commission', url: 'https://europa.eu/youreurope/citizens/travel/carry/animal-plant/index_en.htm', checked: '3 Aug 2026' },
  ] satisfies OfficialSource[],
} as const;

export const portugalGuide = {
  country: 'Portugal', flag: '🇵🇹', title: 'Living in Portugal', subtitle: 'Daily life from Lisbon apartments to smaller Atlantic communities.',
  lastReviewed: '3 August 2026',
  timeSensitiveNote: 'Costs, tax, healthcare access, employment and service information were checked on 3 August 2026. Rules and prices vary by municipality and personal status; verify them with the linked authorities before acting.',
  quickFacts: [{ label: 'Capital', value: 'Lisbon' }, { label: 'Language', value: 'Portuguese' }, { label: 'Currency', value: 'Euro (€)' }, { label: 'Time', value: 'WET · WEST' }],
  cities: [
    { name: 'Lisbon', note: 'Largest international job market, strong transit and the highest rents' }, { name: 'Porto', note: 'Compact northern hub with technology, universities and cooler winters' },
    { name: 'Braga', note: 'Growing technology scene, families and lower costs than Lisbon' }, { name: 'Coimbra', note: 'Historic university city with a younger population' },
    { name: 'Faro', note: 'Algarve services, tourism work and seasonal housing pressure' }, { name: 'Funchal', note: 'Madeira island life, mild weather and remote-worker community' },
  ],
  sections: [
    { title: 'Languages', icon: 'globe', summary: 'Portuguese is essential for public services and deeper local life.', details: ['European Portuguese is used nationally; pronunciation differs notably from Brazilian Portuguese.', 'English is common in tourism, technology and younger urban circles, but contracts and government processes are Portuguese-first.', 'Mirandese has official recognition in its local area. Learning Portuguese substantially improves housing, healthcare and community access.'] },
    { title: 'Climate & seasons', icon: 'sun', summary: 'Mild Atlantic weather, with wetter north and hotter, drier south.', details: ['The north and coast have rainy, humid winters; inland summers can be extremely hot. The Algarve is sunnier and drier.', 'Many homes feel colder indoors than expected because insulation and central heating are inconsistent.', 'Wildfire, drought, heat and coastal flooding affect some areas; follow IPMA and Civil Protection alerts.'] },
    { title: 'Cost of living', icon: 'wallet', summary: 'Everyday costs can be moderate, but housing has risen far faster than local wages.', details: ['Lisbon, Porto and much of the Algarve have pressured rental markets. Smaller inland cities generally cost less but offer fewer jobs and services.', 'Groceries, cafés and public transport may compare favourably with northern Europe; electricity, cars and imported goods can be expensive.', 'Budget from current local listings and official price data rather than old “cheap Portugal” estimates. Checked 3 August 2026.'] },
    { title: 'Healthcare', icon: 'heart', summary: 'The public SNS coexists with widely used private care.', details: ['Eligible residents register at a local health centre and receive an SNS user number; access depends on residence and immigration status.', 'Public care is broad, but family-doctor shortages and specialist waits vary by area.', 'Private insurance and clinics are common for faster access. Confirm coverage, exclusions and whether a clinic has English-speaking staff.'] },
    { title: 'Public transportation', icon: 'plane', summary: 'Car-free life works in Lisbon and Porto; coverage thins quickly elsewhere.', details: ['Lisbon and Porto combine metro, suburban rail, buses and trams. Intercity rail and coaches link major centres.', 'Service can be sparse in rural and coastal communities, and late-night options are limited outside urban cores.', 'Hills, cobbles and heat affect walking accessibility. Island and remote mainland life often requires a car.'] },
    { title: 'Housing market', icon: 'home', summary: 'High demand, limited supply and variable building comfort.', details: ['Expect identification, tax number, income evidence, deposit and sometimes a guarantor or advance rent. Insist on a registered lease and receipts.', 'Check damp, mould, glazing, heating, summer heat, noise and the exact internet connection before signing.', 'Short-term tourism demand affects central Lisbon, Porto, Madeira and the Algarve. Never pay before verifying the owner and property.'] },
    { title: 'Employment market', icon: 'briefcase', summary: 'Tourism, services and technology lead, while Portuguese salaries remain relatively low.', details: ['Lisbon has the broadest international market; Porto, Braga and Aveiro have growing technology and industrial clusters.', 'Portuguese is required for most local roles. Multilingual customer service and international companies offer some English-first work.', 'Non-EU citizens need appropriate work authorization; remote work also creates immigration, payroll and tax questions. Checked 3 August 2026.'] },
    { title: 'Education & childcare', icon: 'document', summary: 'Public schools teach in Portuguese; international options cluster near Lisbon and Porto.', details: ['School quality and capacity vary locally. Address can influence placement, so research before choosing housing.', 'Public and subsidized early-years places can have waiting lists; apply early and confirm municipal rules.', 'Public universities offer comparatively accessible tuition, with English-taught options more common at postgraduate level.'] },
    { title: 'Banking & payments', icon: 'credit-card', summary: 'Cards and the Multibanco network are central to everyday payments.', details: ['A Portuguese tax number (NIF), identification and address evidence are commonly needed to open an account.', 'Multibanco supports payments, transfers and government services; MB WAY is widely used for mobile payments.', 'Some small businesses prefer Portuguese cards or cash. Compare maintenance, transfer and foreign-exchange fees.'] },
    { title: 'Internet & mobile', icon: 'globe', summary: 'Fast urban broadband and strong mobile service, with address-level gaps.', details: ['Fibre is common in cities, but coverage and provider choice must be checked for the exact home.', 'Mobile packages are competitive, though contracts may bundle television and fixed service for long terms.', 'Remote workers should test speeds, backup mobile coverage and power reliability before committing. Checked 3 August 2026.'] },
    { title: 'Tax overview', icon: 'document', summary: 'Tax residence and social security require planning before arrival.', details: ['Residents are generally taxed on worldwide income under progressive rates, subject to treaty rules and personal circumstances.', 'The former broad NHR regime changed; transitional and newer incentive rules are narrower and should not be assumed to apply.', 'Obtain advice before remote work, incorporating a company or relying on a special regime. Checked 3 August 2026.'] },
    { title: 'Safety', icon: 'check', summary: 'Generally safe, with petty theft and environmental hazards the main practical concerns.', details: ['Watch belongings on crowded Lisbon trams, metros and tourist streets.', 'Wildfires, extreme heat, rough seas and earthquakes are relevant regional risks. Learn local evacuation and alert channels.', 'Emergency number 112 operates nationally; understand local healthcare routes before an urgent need.'] },
    { title: 'Culture & etiquette', icon: 'sparkle', summary: 'Courtesy, patience and personal relationships make daily life smoother.', details: ['Use greetings in shops and offices, and avoid assuming Spanish will substitute for Portuguese.', 'Meals run later than in some countries; family and community ties are important.', 'Bureaucracy can be appointment-led and document-heavy. Polite persistence and organized paper copies help.'] },
    { title: 'Work-life balance', icon: 'clock', summary: 'A relaxed public rhythm does not mean every workplace is low-pressure.', details: ['Leave and hours are shaped by labour law and collective agreements, but culture varies by employer and sector.', 'Long lunches are less universal than stereotypes suggest; commuting and split tourism shifts can extend the day.', 'Clarify overtime, remote-work costs, holiday timing and after-hours expectations in writing.'] },
    { title: 'English usage', icon: 'globe', summary: 'High in tourist and international settings, limited in many essential interactions.', details: ['English is widely spoken among younger people and in Lisbon, Porto, Madeira and the Algarve.', 'Healthcare reception, landlords, tradespeople and municipal offices may be Portuguese-only.', 'Learning Portuguese is important for integration and prevents dependence on informal translation.'] },
    { title: 'Accessibility', icon: 'walk', summary: 'Modern systems are improving, but hills, cobbles and older buildings remain major barriers.', details: ['Historic Lisbon and Porto can be steep, uneven and difficult for wheelchairs or low-mobility residents.', 'Step-free transport varies by station, vehicle and outage status. Confirm routes directly with operators.', 'Inspect lifts, entrances and bathrooms personally; “ground floor” descriptions can be misleading on slopes.'] },
    { title: 'LGBTQ+ life', icon: 'heart', summary: 'Strong legal recognition and visible city communities, with regional social differences.', details: ['Marriage equality and legal gender-recognition frameworks exist, but lived experience still differs by community.', 'Lisbon and Porto have the most visible organizations, venues and events.', 'Check current family, healthcare and document procedures with official or specialist sources. Checked 3 August 2026.'] },
    { title: 'Pets', icon: 'heart', summary: 'Pets are common, while entry, registration and housing need advance planning.', details: ['EU pet movement generally requires identification, rabies vaccination and a passport; non-EU entry depends on origin.', 'Dogs require local registration and applicable licensing. Landlords may be reluctant even where blanket prohibitions are restricted.', 'Heat, parasites, airline rules and limited rental supply are practical relocation considerations. Checked 3 August 2026.'] },
  ] satisfies GuideSection[],
  suitability: [{ label: 'Remote workers', fit: 'Good fit', note: 'Strong internet and communities; resolve visa and tax status first.' }, { label: 'Families', fit: 'Good fit', note: 'Safe community life, with school and childcare capacity varying locally.' }, { label: 'Students', fit: 'Good fit', note: 'Historic universities and lively cities; Portuguese expands course and work options.' }, { label: 'Retirees', fit: 'Good fit', note: 'Climate and lifestyle appeal, but healthcare access and tax need local review.' }, { label: 'Entrepreneurs', fit: 'Mixed fit', note: 'Growing ecosystems meet modest domestic demand and administrative friction.' }, { label: 'Outdoor enthusiasts', fit: 'Great fit', note: 'Atlantic coast, islands, hiking and year-round outdoor access.' }, { label: 'Car-free living', fit: 'City dependent', note: 'Very workable in Lisbon and Porto, much harder in rural areas.' }, { label: 'Lower-cost living', fit: 'City dependent', note: 'Possible inland, but not in the most in-demand coastal markets.' }],
  advantages: ['Mild climate and extensive Atlantic coastline', 'Safe, sociable everyday environment', 'Strong urban internet and mobile service', 'Walkable centres and good city transit'],
  disadvantages: ['Housing costs far outpace many local salaries', 'Damp or poorly heated older homes', 'Slow administrative appointments', 'Car dependence outside major urban areas'],
  newcomerDifficulties: ['Finding a legitimate long-term rental', 'Sequencing NIF, bank, address, residence and healthcare setup', 'Understanding tax changes and remote-work obligations', 'Getting timely appointments and Portuguese-language support'],
  wishIKnew: ['Winter indoor comfort matters as much as outdoor temperature.', 'A beautiful coastal town may have few year-round rentals or buses.', 'Do not build a budget from pre-2020 rent anecdotes.', 'Portuguese opens doors that English-speaking expat networks cannot.'],
  sources: [{ label: 'Living and working conditions', organization: 'European Commission · EURES', url: 'https://eures.europa.eu/living-and-working/living-and-working-conditions/living-and-working-conditions-portugal_en', checked: '3 Aug 2026' }, { label: 'Immigration and residence', organization: 'AIMA', url: 'https://aima.gov.pt/en', checked: '3 Aug 2026' }, { label: 'National Health Service', organization: 'SNS', url: 'https://www.sns.gov.pt/', checked: '3 Aug 2026' }, { label: 'Tax services', organization: 'Autoridade Tributária', url: 'https://info.portaldasfinancas.gov.pt/', checked: '3 Aug 2026' }, { label: 'Official statistics', organization: 'Statistics Portugal', url: 'https://www.ine.pt/', checked: '3 Aug 2026' }, { label: 'Weather warnings', organization: 'IPMA', url: 'https://www.ipma.pt/en/', checked: '3 Aug 2026' }, { label: 'Civil protection', organization: 'ANEPC', url: 'https://prociv.gov.pt/en/', checked: '3 Aug 2026' }] satisfies OfficialSource[],
} as const;

export const spainGuide = {
  country: 'Spain', flag: '🇪🇸', title: 'Living in Spain', subtitle: 'A regional, practical guide to work, housing and everyday life.',
  lastReviewed: '3 August 2026', timeSensitiveNote: 'Costs, tax, healthcare access, employment and service information were checked on 3 August 2026. Autonomous communities and municipalities administer many services differently; verify details locally before acting.',
  quickFacts: [{ label: 'Capital', value: 'Madrid' }, { label: 'Language', value: 'Spanish + regional' }, { label: 'Currency', value: 'Euro (€)' }, { label: 'Time', value: 'CET · CEST / Canaries WET' }],
  cities: [{ name: 'Madrid', note: 'Largest job market, central rail hub and hot, dry summers' }, { name: 'Barcelona', note: 'International business and coastal life with very high housing demand' }, { name: 'Valencia', note: 'Cyclable Mediterranean city with growing technology scene' }, { name: 'Seville', note: 'Andalusian capital with lower rents and extreme summer heat' }, { name: 'Bilbao', note: 'Industry, services and green northern surroundings' }, { name: 'Málaga', note: 'Technology and tourism growth with a pressured coastal rental market' }],
  sections: [
    { title: 'Languages', icon: 'globe', summary: 'Spanish is national; several regions use co-official languages every day.', details: ['Castilian Spanish is official nationwide. Catalan/Valencian, Galician, Basque and Aranese have co-official status in their territories.', 'Schooling and government communication may primarily use the regional language, depending on location.', 'English helps in international sectors but Spanish—and sometimes the regional language—is important for work and integration.'] },
    { title: 'Climate & seasons', icon: 'sun', summary: 'Atlantic, Mediterranean, continental and island climates differ dramatically.', details: ['Central Spain has cold winters and very hot dry summers; the north is cooler, greener and wetter.', 'Mediterranean areas have mild winters, humid summers and episodes of intense rain. The Canaries remain mild year-round and use WET/WEST.', 'Heat, drought, wildfire and flash flooding increasingly shape housing and location choices.'] },
    { title: 'Cost of living', icon: 'wallet', summary: 'Rent dominates budgets in Madrid, Barcelona, islands and popular coastal cities.', details: ['Smaller inland cities can be substantially cheaper, but employment and transport choices narrow.', 'Groceries and public transport are often reasonable relative to northern Europe; electricity and cooling can raise seasonal bills.', 'Use INE data and current neighbourhood listings, not a national average. Checked 3 August 2026.'] },
    { title: 'Healthcare', icon: 'heart', summary: 'A universal public system delivered by autonomous communities.', details: ['Eligible residents register locally for a health card and are assigned primary care; requirements depend on status.', 'Public quality is generally strong, with regional differences in access and specialist waiting times.', 'Private insurance is common for speed and may be required by particular visa routes; confirm policy conditions carefully.'] },
    { title: 'Public transportation', icon: 'plane', summary: 'Excellent high-speed rail and strong big-city networks.', details: ['Madrid, Barcelona, Valencia, Bilbao and other cities support car-free living through metro, rail, tram, bus and cycling.', 'High-speed rail links many major centres, while rural, island and peripheral routes are less comprehensive.', 'Low-emission zones, parking restrictions and heat should factor into car and neighbourhood decisions.'] },
    { title: 'Housing market', icon: 'home', summary: 'High-demand markets move quickly and rental rules are actively changing.', details: ['Landlords commonly request income evidence, deposit and guarantees. Obtain a written, lawful contract and inventory.', 'Check cooling, insulation, street noise, lift access, community charges and tourist activity.', 'Fraud and illegal advance demands target newcomers. Rental regulation varies and changes; verify with regional housing authorities. Checked 3 August 2026.'] },
    { title: 'Employment market', icon: 'briefcase', summary: 'Large and diverse, but unemployment and temporary work remain significant.', details: ['Madrid and Barcelona lead international hiring; technology clusters also exist in Valencia, Málaga, Bilbao and elsewhere.', 'Tourism, logistics, renewable energy, automotive, agriculture and services are major sectors.', 'Spanish is required for most roles. Non-EU workers need authorization, and regulated professions may require qualification recognition.'] },
    { title: 'Education & childcare', icon: 'document', summary: 'Public, concertado and private options vary by region and language policy.', details: ['Public schools are free at compulsory levels; placement and teaching language depend on region and address.', 'Subsidized concertado schools may have additional costs. International schools are concentrated in larger and coastal cities.', 'Early-years availability and fees vary locally, so families should apply early and confirm calendars and language models.'] },
    { title: 'Banking & payments', icon: 'credit-card', summary: 'Cards and contactless payments are widespread, though an account simplifies resident life.', details: ['Banks usually request identification, address and NIE/TIE details; resident and non-resident account terms differ.', 'An Spanish IBAN simplifies rent, payroll, utilities and direct debits, although EU IBAN discrimination is unlawful.', 'Compare account, card, ATM and transfer fees; cash is still useful for small purchases.'] },
    { title: 'Internet & mobile', icon: 'globe', summary: 'Extensive fibre coverage and competitive mobile service.', details: ['Urban fibre is generally fast, but exact-building availability must be confirmed.', 'Bundled contracts are common; read minimum-term and installation terms before signing.', 'Rural and island coverage varies. Remote workers should verify upload speed and backup mobile reception. Checked 3 August 2026.'] },
    { title: 'Tax overview', icon: 'document', summary: 'Residence can trigger worldwide-income reporting and regional variation.', details: ['Tax residence is determined under domestic rules and treaties; residents generally report worldwide income.', 'Income tax combines national and autonomous-community elements. Wealth and asset-reporting obligations may apply.', 'The inbound-worker regime has strict conditions. Seek cross-border advice before moving, incorporating or working remotely. Checked 3 August 2026.'] },
    { title: 'Safety', icon: 'check', summary: 'Generally safe, with theft and climate hazards the common practical risks.', details: ['Pickpocketing is concentrated on crowded transport and tourist corridors in major cities.', 'Heatwaves, wildfires and flash floods can be severe. Follow AEMET and Civil Protection guidance.', 'Emergency number 112 works nationwide. Learn local beach, mountain and road risks.'] },
    { title: 'Culture & etiquette', icon: 'sparkle', summary: 'Social life runs late and regional identity deserves respect.', details: ['Greeting people and taking time for conversation matter; meal and evening schedules are later than in much of Europe.', 'Spain is culturally and linguistically diverse. Avoid reducing regions to national stereotypes.', 'Appointments, certified copies and digital identity systems are central to administration.'] },
    { title: 'Work-life balance', icon: 'clock', summary: 'Strong social life and leave rights coexist with varied working cultures.', details: ['Schedules vary: office workers may finish late, while tourism and retail involve split or weekend shifts.', 'Hybrid work is established in some professional sectors but should be confirmed contractually.', 'Clarify collective agreement, hours, overtime, remote-work costs and summer scheduling.'] },
    { title: 'English usage', icon: 'globe', summary: 'Useful in tourism and global companies, but not enough for independent resident life.', details: ['English use is highest in international workplaces, universities and tourist regions.', 'Public administration, healthcare, housing and trades are generally Spanish-first.', 'Spanish greatly expands employment and social opportunities; regional languages can matter in schools and public roles.'] },
    { title: 'Accessibility', icon: 'walk', summary: 'Modern transit is often accessible, while historic fabric and local delivery vary.', details: ['Many metro, tram and bus systems provide step-free features, but outages and station gaps occur.', 'Old centres can have cobbles, slopes and buildings without lifts. Newer districts are often easier.', 'Confirm exact transport routes and measure home access rather than relying on listing labels.'] },
    { title: 'LGBTQ+ life', icon: 'heart', summary: 'Broad legal recognition and visible communities, with uneven lived experience.', details: ['Marriage equality and national anti-discrimination protections are established.', 'Madrid, Barcelona, Valencia and other cities have large communities and services; acceptance can still vary locally.', 'Trans, family and documentation procedures can change; consult current official guidance. Checked 3 August 2026.'] },
    { title: 'Pets', icon: 'heart', summary: 'Pets are widespread, with national entry rules and regional ownership obligations.', details: ['EU movement generally requires microchip, rabies vaccination and pet passport; non-EU requirements depend on origin.', 'Registration, insurance and dog-handling requirements can vary by region, municipality and animal category.', 'Heat, rental restrictions and transport rules should be planned before arrival. Checked 3 August 2026.'] },
  ] satisfies GuideSection[],
  suitability: [{ label: 'Remote workers', fit: 'Good fit', note: 'Excellent connectivity and city choice; settle authorization and tax first.' }, { label: 'Families', fit: 'Good fit', note: 'Strong public services, with school language and housing key to location.' }, { label: 'Students', fit: 'Great fit', note: 'Many universities, active cities and comparatively broad course choice.' }, { label: 'Retirees', fit: 'Good fit', note: 'Climate and healthcare appeal; avoid assuming every coast is inexpensive.' }, { label: 'Entrepreneurs', fit: 'Good fit', note: 'Large market and growing hubs, with substantial administration.' }, { label: 'Outdoor enthusiasts', fit: 'Great fit', note: 'Mountains, Atlantic and Mediterranean coasts, islands and national parks.' }, { label: 'Car-free living', fit: 'Great in cities', note: 'Strong urban transit and rail; rural coverage is less consistent.' }, { label: 'Lower-cost living', fit: 'City dependent', note: 'Possible inland and in smaller cities, away from pressured hubs.' }],
  advantages: ['Diverse cities, climates and regional cultures', 'Strong public transport and high-speed rail', 'Broad public healthcare system', 'Social, outdoor-oriented daily life'], disadvantages: ['High rents in major and coastal markets', 'Complex national and regional administration', 'Hotter summers and growing climate risk', 'Spanish needed for most employment and services'], newcomerDifficulties: ['Securing housing from abroad', 'Sequencing NIE/TIE, registration, banking and healthcare', 'Understanding autonomous-community differences', 'Managing tax and social-security rules for remote work'], wishIKnew: ['Choose a region as carefully as a country; language, tax and services differ.', 'A south-facing top-floor flat can be punishing in summer.', 'Digital certificates make administration much easier once set up.', 'Coastal popularity does not guarantee year-round housing or work.'],
  sources: [{ label: 'Living and working conditions', organization: 'European Commission · EURES', url: 'https://eures.europa.eu/living-and-working/living-and-working-conditions/living-and-working-conditions-spain_en', checked: '3 Aug 2026' }, { label: 'Immigration portal', organization: 'Government of Spain', url: 'https://www.inclusion.gob.es/web/migraciones/', checked: '3 Aug 2026' }, { label: 'National Health System', organization: 'Ministry of Health', url: 'https://www.sanidad.gob.es/en/home.htm', checked: '3 Aug 2026' }, { label: 'Tax agency', organization: 'Agencia Tributaria', url: 'https://sede.agenciatributaria.gob.es/', checked: '3 Aug 2026' }, { label: 'Official statistics', organization: 'INE', url: 'https://www.ine.es/en/', checked: '3 Aug 2026' }, { label: 'Weather warnings', organization: 'AEMET', url: 'https://www.aemet.es/en/portada', checked: '3 Aug 2026' }, { label: 'Housing information', organization: 'Ministry of Housing', url: 'https://www.lamoncloa.gob.es/lang/en/ministerios/mivau/Paginas/index.aspx', checked: '3 Aug 2026' }] satisfies OfficialSource[],
} as const;

export const countryGuides = { Italy: italyGuide, Portugal: portugalGuide, Spain: spainGuide } as const;
export type SupportedGuideCountry = keyof typeof countryGuides;
export type CountryGuide = (typeof countryGuides)[SupportedGuideCountry];